version: "3.9"

services:
  web:
    command: gunicorn bookstore.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_ENV=prod
    env_file:
      - .env.prod
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media

  db:
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
  static_volume:
  media_volume:
